"""
Django settings for QSHOP project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e60&y4p0-h+#bqc6#_tyfkyy-j!qt*l6yu5c775(k%wis)=di('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #添加的app
    'ckeditor',
    'ckeditor_uploader',
    'manager.apps.ManagerConfig',
    'goods.apps.GoodsConfig',
    'user.apps.UserConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "QSHOP.middleware.MiddleWareIp"
]

ROOT_URLCONF = 'QSHOP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'QSHOP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',  #配置链接mysql数据库
        'NAME': 'qshop',                       #要连接的数据库名称
        'HOST':'127.0.0.1',                    #数据库的ip地址
        'USER':'root',                         #数据库的用户名
        'PASSWORD':'morning321',                     #数据库密码
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

#静态文件的存储路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]

#用户上传文件的存储路径
MEDIA_ROOT= os.path.join(BASE_DIR,'static')

#用于静态收集路径：将app中的静态文件收集到指定文件夹下
# STATIC_ROOT = os.path.join(BASE_DIR,'static')


CKEDITOR_UPLOAD_PATH = 'content/ckeditor'

#配置邮箱
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#smtp服务的邮箱服务器，163邮箱
EMAIL_HOST = 'smtp.163.com'
#smtp服务固定的端口
EMAIL_PORT = 25  #994
#发件人的邮箱
EMAIL_HOST_USER = '18737307883@163.com'
EMAIL_HOST_PASSWORD = 'lh111111'
EMAIL_FROM = '优选农产品<18737307883@163.com>'


SESSION_EXPIRE_AT_BROWSER_CLOSE=True  # 关闭浏览器cookie 失效