# Generated by Django 2.1.8 on 2019-11-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('goods', '0002_auto_20191117_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goods_oprice', models.FloatField(verbose_name='现价')),
                ('goods_xprice', models.FloatField(verbose_name='原价')),
                ('gooods_count', models.IntegerField(default=0, verbose_name='商品数量')),
                ('goods_production', models.DateTimeField(auto_now=True, verbose_name='生产日期')),
                ('safe_date', models.CharField(max_length=10, verbose_name='保质期')),
                ('goods_method', models.CharField(max_length=100, verbose_name='存储方法')),
                ('goods_description', models.CharField(max_length=100, verbose_name='商品简介')),
                ('goods_pic', models.ImageField(upload_to='media/goods/image', verbose_name='商品图片')),
                ('goods_address', models.CharField(max_length=50, verbose_name='配送地址')),
                ('goods_info', models.TextField(verbose_name='商品详情')),
                ('status', models.BooleanField(default=1, verbose_name='商品状态')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Manager', verbose_name='商家')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Type', verbose_name='类别')),
            ],
            options={
                'verbose_name_plural': '商品',
                'verbose_name': '商品',
            },
        ),
    ]
