# Generated by Django 2.1.8 on 2019-11-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='gooods_count',
            new_name='goods_count',
        ),
    ]
