# Generated by Django 2.1.8 on 2019-12-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20191130_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(max_length=100, verbose_name='商品名称'),
        ),
    ]
