# Generated by Django 2.1.8 on 2019-12-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191204_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.TextField(verbose_name='商品名称'),
        ),
    ]
