# Generated by Django 2.1.8 on 2019-12-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20191204_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(verbose_name='商品简介'),
        ),
    ]
