# Generated by Django 2.1.8 on 2019-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='商家邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='商家密码')),
                ('image', models.ImageField(default='media/user/image/user_default.jpg', upload_to='media/user/image')),
                ('is_login', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': '买家用户',
                'verbose_name': '买家用户',
            },
        ),
    ]
