# Generated by Django 2.1.8 on 2019-12-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191206_2003'),
        ('goods', '0007_auto_20191211_1135'),
        ('user', '0003_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_code', models.CharField(max_length=14, unique=True, verbose_name='订单总编号')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contacts', models.CharField(max_length=30, verbose_name='收货人')),
                ('address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('pay_status', models.BooleanField(default=0, verbose_name='支付状态')),
                ('pay_time', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('total_money', models.FloatField(verbose_name='价格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', verbose_name='买家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=32, verbose_name='订单详细编号')),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('money', models.FloatField(verbose_name='价格')),
                ('send_status', models.BooleanField(default=0, verbose_name='发货状态')),
                ('send_time', models.DateTimeField(null=True, verbose_name='发货时间')),
                ('receive_status', models.BooleanField(default=0, verbose_name='收货状态')),
                ('receive_time', models.DateTimeField(null=True, verbose_name='收货时间')),
                ('comment_status', models.BooleanField(default=0, verbose_name='评价状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Goods', verbose_name='商品')),
                ('manage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Manager', verbose_name='商家')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Order', verbose_name='订单编号')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
    ]
