# Generated by Django 2.1.8 on 2019-12-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_order_order_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_code',
            field=models.CharField(max_length=17, unique=True, verbose_name='订单总编号'),
        ),
    ]
