# Generated by Django 2.1.8 on 2019-12-25 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191225_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_info',
            old_name='manage',
            new_name='manager',
        ),
        migrations.AlterField(
            model_name='order_info',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Order', verbose_name='订单'),
        ),
    ]
