# Generated by Django 2.1.8 on 2019-12-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20191211_1135'),
        ('user', '0006_auto_20191225_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='买家')),
            ],
            options={
                'verbose_name_plural': '买家爱好',
                'verbose_name': '买家爱好',
            },
        ),
    ]
