# Generated by Django 2.1.8 on 2019-12-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_hobby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
