# Generated by Django 2.1.8 on 2020-01-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191230_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_score', models.FloatField(verbose_name='商品评分')),
                ('servic_secore', models.FloatField(verbose_name='客服评分')),
                ('logistics_score', models.FloatField(verbose_name='物流评分')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('shop_reply', models.TextField(verbose_name='商家回复')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='商家回复时间')),
                ('is_anonymous', models.BooleanField(verbose_name='是否匿名评价')),
                ('orderinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Order_info', verbose_name='订单详情')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='买家用户')),
            ],
            options={
                'verbose_name_plural': '商品评价',
                'verbose_name': '商品评价',
            },
        ),
    ]
