# Generated by Django 2.1.8 on 2020-01-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='servic_secore',
            new_name='service_score',
        ),
    ]
